/// 문제 덤프
/// 
/// 이 파일은 개발 및 테스트용 문제 데이터를 정의합니다.
/// 실제 앱에서는 서버에서 데이터를 가져옵니다.
/// 
/// 작성자: 개발팀
/// 작성일: 2024
/// 버전: 1.0.0
import "question.dart";

/// 샘플 문제는 아래와 같이 등록합니다:
/// 
/// Question(
///   id: "1",
///   question: "클라우드 컴퓨팅의 주요 특징 중 하나로 올바르게 설명된 것은 무엇인가?",
///   type: "STAFF",
///   options: [
///     "A. 사용자는 물리적인 서버 위치를 직접 제어해야 한다.",
///     "B. 클라우드 자원은 구매 후 수개월 후에 사용 가능하다.",
///     "C. 필요한 만큼 자원을 사용하고 이에 따라 비용을 지불한다.",
///     "D. 모든 클라우드 서비스는 동일한 보안 수준을 제공한다.",
///     "E. 클라우드는 오직 대기업만 사용할 수 있는 기술이다."
///   ],
///   correctAnswer: 2,
///   answer: true,
///   explanation: "클라우드 컴퓨팅은 온디맨드 방식으로 자원을 제공하며, 사용량 기반 과금(pay-as-you-go)이 주요 특징 중 하나이다.",
///   createdAt: DateTime.now(),
///   group: "staff",
///   difficulty: "하",
///   score: 10,
///   topic: "Cloud",
///   title: "클라우드 컴퓨팅의 기본 개념",
///   intent: "클라우드의 핵심 특징에 대한 이해도 확인",
///   reference: "STAFF 교재 2장 1절 p.27"
/// ),

/// 문제 데이터
final List<Question> sampleQuestions = [
  Question(
    id: "01",
    question: "클라우드 컴퓨팅에서 'Pay-as-you-go' 모델이 의미하는 바는 무엇인가?",
    type: "STAFF",
    options: [
      "A. 초기 구축비용을 미리 지불하는 방식",
      "B. 필요한 자원을 정액제로 계약하는 방식",
      "C. 사용한 만큼만 비용을 지불하는 방식",
      "D. 특정 기간 동안 무료로 사용하는 방식",
      "E. 사용량과 관계없이 고정요금이 청구되는 방식"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "Pay-as-you-go 모델은 실제 사용한 만큼만 비용을 지불하는 클라우드 과금 방식이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "Cloud",
    title: "클라우드 과금 모델 이해",
    intent: "클라우드 서비스의 핵심 개념인 사용량 기반 과금 방식 이해도 평가",
    reference: "STAFF 교재 2장 1절 p.27"
  ),
  Question(
    id: "02",
    question: "애자일(Agile) 방법론의 핵심 가치로 적절하지 않은 것은?",
    type: "STAFF",
    options: [
      "A. 계획보다 변화에 대응",
      "B. 프로세스보다 개인과 상호작용 중시",
      "C. 문서보다 작동하는 소프트웨어 중시",
      "D. 고객과의 협업보다 계약 협상 중시",
      "E. 빠른 피드백을 통한 지속적 개선"
    ],
    correctAnswer: 3,
    answer: true,
    explanation: "Agile은 계약 협상보다 고객과의 협업을 중시하는 방법론이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "Agile",
    title: "Agile 가치 이해",
    intent: "Agile의 기본 가치에 대한 이해도 평가",
    reference: "STAFF 교재 3장 2절 p.45"
  ),
  Question(
    id: "03",
    question: "AI 프로젝트 성공을 위한 주요 고려사항으로 가장 적절한 것은?",
    type: "STAFF",
    options: [
      "A. 데이터 수집보다 알고리즘 선택이 중요하다",
      "B. 모델이 복잡할수록 항상 성능이 좋다",
      "C. 데이터의 품질과 전처리가 중요하다",
      "D. 사후 모니터링은 필요 없다",
      "E. 외부 데이터 사용은 금지해야 한다"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "AI 프로젝트는 고품질 데이터와 전처리 과정이 성공의 핵심 요소이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "AI",
    title: "AI 프로젝트 성공 요건",
    intent: "AI 도입 시 고려해야 할 핵심 요소 파악",
    reference: "STAFF 교재 4장 1절 p.52"
  ),
  Question(
    id: "04",
    question: "다음 중 'Zero Trust' 보안 모델의 핵심 원칙으로 가장 적절한 것은?",
    type: "STAFF",
    options: [
      "A. 내부 사용자는 모두 신뢰한다",
      "B. 일단 인증되면 모든 리소스 접근이 가능하다",
      "C. 항상 검증하고 최소 권한을 부여한다",
      "D. 외부 공격만 방어하면 충분하다",
      "E. 보안은 인프라 팀의 책임이다"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "Zero Trust는 '아무도 신뢰하지 않고 항상 검증하며 최소 권한을 부여'하는 보안 모델이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "상",
    score: 10,
    topic: "보안",
    title: "Zero Trust 보안 모델 이해",
    intent: "최신 보안 접근법인 Zero Trust의 개념과 적용 원칙 파악",
    reference: "STAFF 교재 6장 1절 p.78"
  ),
  Question(
    id: "05",
    question: "데이터 레이크(Data Lake)와 데이터 웨어하우스(Data Warehouse)의 주요 차이점은 무엇인가?",
    type: "STAFF",
    options: [
      "A. 데이터 웨어하우스는 정형 데이터를 저장하지 않는다",
      "B. 데이터 레이크는 주로 비정형 데이터를 저장한다",
      "C. 둘 다 동일한 아키텍처를 사용한다",
      "D. 데이터 레이크는 사전 정의된 스키마가 필요하다",
      "E. 데이터 웨어하우스는 비정형 데이터에 최적화되어 있다"
    ],
    correctAnswer: 1,
    answer: true,
    explanation: "데이터 레이크는 비정형 데이터를 포함한 다양한 형태의 데이터를 저장하는 시스템이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Data",
    title: "데이터 저장 아키텍처 이해",
    intent: "데이터 아키텍처 간 차이점 이해도 평가",
    reference: "STAFF 교재 5장 2절 p.65"
  ),
  Question(
    id: "06",
    question: "클라우드 환경에서 '멀티 테넌시(Multi-tenancy)'가 의미하는 것은?",
    type: "STAFF",
    options: [
      "A. 하나의 물리 서버에 하나의 고객만 사용하는 구조",
      "B. 여러 조직이 각자 전용 서버를 사용하는 구조",
      "C. 하나의 인프라를 여러 고객이 공유하는 구조",
      "D. 고객마다 별도의 보안 체계를 구축하는 방식",
      "E. 클라우드 공급자가 내부적으로만 사용하는 방식"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "멀티 테넌시는 하나의 물리적 인프라를 여러 고객이 논리적으로 분리해 사용하는 클라우드 구조이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Cloud",
    title: "클라우드 멀티 테넌시 개념",
    intent: "클라우드 운영 모델의 기본 구조 이해",
    reference: "STAFF 교재 2장 2절 p.30"
  ),
  Question(
    id: "07",
    question: "Agile에서 스프린트 리뷰(Sprint Review)의 주요 목적은?",
    type: "STAFF",
    options: [
      "A. 다음 스프린트 계획 수립",
      "B. 산출물의 고객 피드백 수집",
      "C. 기술적 부채 정리",
      "D. 팀 구성 변경",
      "E. 예산 조정 회의"
    ],
    correctAnswer: 1,
    answer: true,
    explanation: "스프린트 리뷰는 제품 증분을 공유하고 고객 피드백을 반영하는 자리이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "Agile",
    title: "Agile의 스프린트 리뷰 목적",
    intent: "Agile 실행 절차에 대한 이해도 점검",
    reference: "STAFF 교재 3장 3절 p.47"
  ),
  Question(
    id: "08",
    question: "CX(고객경험) 전략 수립 시 가장 먼저 고려해야 할 요소는?",
    type: "STAFF",
    options: [
      "A. 비용 절감 방안",
      "B. 내부 인프라 개선",
      "C. 고객 여정 파악",
      "D. SNS 마케팅 전략",
      "E. 경쟁사 벤치마킹"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "고객경험 전략은 고객 여정 이해에서 출발해야 하며, 이를 바탕으로 각 접점에서의 개선을 추진한다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "CX",
    title: "CX 전략 수립 핵심",
    intent: "고객경험 중심 사고 기반 전략 접근 이해",
    reference: "STAFF 교재 5장 1절 p.60"
  ),
  Question(
    id: "09",
    question: "다음 중 Application Modernization의 주요 목적이 아닌 것은?",
    type: "STAFF",
    options: [
      "A. 유지보수 비용 증가",
      "B. 유연성 향상",
      "C. 기술 부채 해소",
      "D. 레거시 시스템의 현대화",
      "E. 클라우드 네이티브화"
    ],
    correctAnswer: 0,
    answer: true,
    explanation: "Application Modernization은 유지보수 비용을 줄이고 유연성을 높이는 것을 목표로 한다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Application Modernization",
    title: "Application Modernization 목적",
    intent: "현대화 프로젝트의 필요성과 목표 이해도 점검",
    reference: "STAFF 교재 3장 1절 p.42"
  ),
  Question(
    id: "10",
    question: "AI 모델 운영 과정에서 '드리프트(Drift)'가 발생했을 때 적절한 대응은?",
    type: "STAFF",
    options: [
      "A. 모델을 그대로 유지한다",
      "B. 더 큰 데이터셋으로 학습시킨다",
      "C. 주기적인 재학습 또는 재검증을 수행한다",
      "D. 모델 복잡도를 줄인다",
      "E. 하드웨어를 교체한다"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "데이터 또는 환경이 변해 모델 성능이 저하되는 드리프트 상황에서는 재학습 및 검증이 필요하다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "상",
    score: 10,
    topic: "AI",
    title: "AI 운영 중 드리프트 대응",
    intent: "모델 운영 시 발생할 수 있는 이슈 및 대응 방법 이해",
    reference: "STAFF 교재 4장 2절 p.54"
  ),
  Question(
    id: "11",
    question: "클라우드에서 'IaaS(서비스형 인프라)'가 제공하는 것은?",
    type: "STAFF",
    options: [
      "A. 소프트웨어 애플리케이션",
      "B. 데이터 분석 기능",
      "C. 서버, 스토리지, 네트워크 등 인프라 자원",
      "D. 고객 맞춤형 UI 디자인",
      "E. 마케팅 자동화 솔루션"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "IaaS는 서버, 스토리지, 네트워크 등의 인프라를 가상화 환경에서 제공하는 서비스이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "Cloud",
    title: "IaaS 정의",
    intent: "클라우드 서비스 유형에 대한 이해",
    reference: "STAFF 교재 2장 1절 p.26"
  ),
  Question(
    id: "12",
    question: "다음 중 CX 개선 활동의 일환으로 보기 어려운 것은?",
    type: "STAFF",
    options: [
      "A. 고객 VOC 분석",
      "B. 고객 여정 지도 작성",
      "C. 콜센터 상담 품질 향상",
      "D. 서버 메모리 최적화",
      "E. 사용자 피드백 기반 서비스 개선"
    ],
    correctAnswer: 3,
    answer: true,
    explanation: "서버 메모리 최적화는 고객경험보다는 기술 운영 측면에 가까운 활동이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "CX",
    title: "CX 개선 범위 식별",
    intent: "CX 관련 활동과 일반 IT 운영 활동 구분 능력 확인",
    reference: "STAFF 교재 5장 1절 p.60"
  ),
  Question(
    id: "13",
    question: "다음 중 AI 윤리 원칙에 해당하지 않는 것은?",
    type: "STAFF",
    options: [
      "A. 투명성",
      "B. 공정성",
      "C. 책임성",
      "D. 편향성 유지",
      "E. 안전성"
    ],
    correctAnswer: 3,
    answer: true,
    explanation: "AI 윤리는 편향을 줄이는 방향으로 설계되며, 편향성 유지는 바람직하지 않다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "AI",
    title: "AI 윤리 원칙 이해",
    intent: "AI 활용 시 고려해야 할 윤리적 기준 인식",
    reference: "STAFF 교재 4장 3절 p.56"
  ),
  Question(
    id: "14",
    question: "애자일 방법론에서 '스크럼 마스터'의 역할로 적절한 것은?",
    type: "STAFF",
    options: [
      "A. 제품 백로그 우선순위 결정",
      "B. 개발 업무 직접 수행",
      "C. 장애물 제거 및 팀 지원",
      "D. 고객과 계약 조건 협상",
      "E. 테스트 자동화 수행"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "스크럼 마스터는 팀이 Agile을 잘 수행하도록 돕고 장애물을 제거하는 역할을 한다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "Agile",
    title: "스크럼 마스터 역할",
    intent: "애자일 구성원 역할의 이해도 평가",
    reference: "STAFF 교재 3장 3절 p.46"
  ),
  Question(
    id: "15",
    question: "데이터 거버넌스(Data Governance)의 주요 목적은?",
    type: "STAFF",
    options: [
      "A. 데이터 저장소 구축",
      "B. 데이터 과학자 고용",
      "C. 데이터 품질 및 보안 기준 관리",
      "D. 데이터 백업 주기 설정",
      "E. 데이터 암호화 알고리즘 개발"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "데이터 거버넌스는 데이터 품질, 보안, 정책 등을 통합적으로 관리하는 체계이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Data",
    title: "데이터 거버넌스 개념",
    intent: "데이터 관리 체계에 대한 이해 평가",
    reference: "STAFF 교재 5장 1절 p.62"
  ),
  Question(
    id: "16",
    question: "클라우드 전환 시 'Lift and Shift' 전략의 특징으로 가장 적절한 것은?",
    type: "STAFF",
    options: [
      "A. 기존 애플리케이션을 재설계하여 전환",
      "B. 클라우드 네이티브로 완전 재구축",
      "C. 최소한의 수정으로 클라우드로 이동",
      "D. 오픈소스로 대체 후 이전",
      "E. 데이터만 이전하고 애플리케이션은 유지"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "'Lift and Shift'는 기존 시스템을 구조 변경 없이 클라우드로 옮기는 전략이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Cloud",
    title: "Lift and Shift 전략 이해",
    intent: "클라우드 전환 전략에 대한 기본 이해",
    reference: "STAFF 교재 2장 3절 p.33"
  ),
  Question(
    id: "17",
    question: "보안의 3요소(3A)에 해당하지 않는 것은?",
    type: "STAFF",
    options: [
      "A. 인증(Authentication)",
      "B. 권한 부여(Authorization)",
      "C. 감사(Auditing)",
      "D. 접근(Approach)",
      "E. 회수(Accountability)"
    ],
    correctAnswer: 3,
    answer: true,
    explanation: "보안의 3A는 인증, 권한부여, 감사(A&A&A)로 구성되며 접근(Approach)은 포함되지 않는다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "보안",
    title: "보안 핵심 요소 이해",
    intent: "정보보안의 기본 구성요소 개념 파악",
    reference: "STAFF 교재 6장 1절 p.79"
  ),
  Question(
    id: "18",
    question: "Agile 개발의 반복(iteration) 구조가 주는 이점으로 가장 적절한 것은?",
    type: "STAFF",
    options: [
      "A. 전체 개발 후 단일 검증",
      "B. 고객 요구사항 반영이 어려움",
      "C. 지속적인 피드백과 개선 가능",
      "D. 일정이 고정되어 유연성 부족",
      "E. 문서 기반 개발 프로세스 유지"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "Agile은 반복적 개발을 통해 지속적인 피드백과 개선이 가능하다는 장점이 있다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Agile",
    title: "Agile 반복 구조의 장점",
    intent: "Agile 프로세스 구조적 이점 이해",
    reference: "STAFF 교재 3장 2절 p.44"
  ),
  Question(
    id: "19",
    question: "AI 프로젝트 추진 시 가장 먼저 고려해야 할 요소는?",
    type: "STAFF",
    options: [
      "A. 알고리즘 선정",
      "B. 모델 훈련 속도",
      "C. 활용 가능한 데이터 확보",
      "D. 클라우드 인프라 도입",
      "E. 서비스 배포 전략"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "AI는 데이터 기반 기술이므로 프로젝트 시작 전 데이터 확보가 선행되어야 한다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "AI",
    title: "AI 프로젝트 시작 요건",
    intent: "AI 추진 초기 고려사항 파악",
    reference: "STAFF 교재 4장 1절 p.52"
  ),
  Question(
    id: "20",
    question: "데이터 품질 관리의 주요 요소로 볼 수 없는 것은?",
    type: "STAFF",
    options: [
      "A. 정확성",
      "B. 일관성",
      "C. 시의성",
      "D. 용량",
      "E. 완전성"
    ],
    correctAnswer: 3,
    answer: true,
    explanation: "데이터 품질은 정확성, 일관성, 시의성, 완전성 등이 기준이며, '용량'은 해당되지 않는다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Data",
    title: "데이터 품질 요소 식별",
    intent: "데이터 관리 품질 요건 이해",
    reference: "STAFF 교재 5장 2절 p.66"
  ),
  Question(
    id: "21",
    question: "CX 설계 시 '고객 페르소나(Persona)'를 정의하는 목적은?",
    type: "STAFF",
    options: [
      "A. 고객의 실명 확보",
      "B. 내부 프로세스 최적화",
      "C. 마케팅 채널 다변화",
      "D. 고객의 유형별 특성 이해",
      "E. 경쟁사 분석 간소화"
    ],
    correctAnswer: 3,
    answer: true,
    explanation: "고객 페르소나는 다양한 유형의 고객을 이해하고 경험 설계에 반영하기 위해 설정된다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "CX",
    title: "CX 전략에서 페르소나의 역할",
    intent: "고객 페르소나 정의 목적 이해",
    reference: "STAFF 교재 5장 1절 p.61"
  ),
  Question(
    id: "22",
    question: "클라우드 네이티브 아키텍처의 주요 구성 요소로 적절하지 않은 것은?",
    type: "STAFF",
    options: [
      "A. 마이크로서비스",
      "B. 컨테이너",
      "C. CI/CD 파이프라인",
      "D. 단일 모놀리식 애플리케이션",
      "E. 오케스트레이션 도구"
    ],
    correctAnswer: 3,
    answer: true,
    explanation: "모놀리식 구조는 클라우드 네이티브 방식과 반대되는 개념이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "상",
    score: 10,
    topic: "Cloud",
    title: "클라우드 네이티브 아키텍처 요소",
    intent: "클라우드 기반 아키텍처 구성 요소 식별",
    reference: "STAFF 교재 2장 3절 p.35"
  ),
  Question(
    id: "23",
    question: "애플리케이션 현대화 전략 중 'Refactoring'의 의미는?",
    type: "STAFF",
    options: [
      "A. 완전 신규 개발",
      "B. 시스템을 제거하고 아웃소싱",
      "C. 애플리케이션 구조를 최적화하여 유지",
      "D. 기능 축소를 통한 경량화",
      "E. 데이터베이스만 마이그레이션"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "'Refactoring'은 기존 기능을 유지하면서 구조를 개선하는 전략이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Application Modernization",
    title: "Refactoring 전략 이해",
    intent: "애플리케이션 현대화 방식 이해",
    reference: "STAFF 교재 3장 1절 p.43"
  ),
  Question(
    id: "24",
    question: "보안 정책 수립 시 '최소 권한 원칙'이 의미하는 것은?",
    type: "STAFF",
    options: [
      "A. 누구나 모든 데이터에 접근 가능",
      "B. 외부 파트너는 권한 부여 제외",
      "C. 업무 수행에 꼭 필요한 권한만 부여",
      "D. 관리자 권한을 기본값으로 제공",
      "E. 권한은 프로젝트 단위로 자동 배포"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "'최소 권한 원칙'은 불필요한 권한을 제한하고 꼭 필요한 권한만 부여하는 원칙이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "보안",
    title: "최소 권한 보안 원칙",
    intent: "보안 설정 원칙 이해",
    reference: "STAFF 교재 6장 2절 p.81"
  ),
  Question(
    id: "25",
    question: "데이터 분석 기반 의사결정의 장점으로 가장 적절한 것은?",
    type: "STAFF",
    options: [
      "A. 직관에 의한 빠른 판단 가능",
      "B. 감성적 접근 강조",
      "C. 반복적인 경험 중시",
      "D. 객관적 근거 기반 결정 가능",
      "E. 업무 프로세스와 무관함"
    ],
    correctAnswer: 3,
    answer: true,
    explanation: "데이터 기반 의사결정은 객관적인 근거를 제공하여 신뢰성과 일관성을 확보할 수 있다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "Data",
    title: "데이터 기반 의사결정 장점",
    intent: "데이터 분석 활용 목적 이해",
    reference: "STAFF 교재 5장 1절 p.63"
  ),
  Question(
    id: "26",
    question: "데이터 분석에서 'EDA(Exploratory Data Analysis)'의 주요 목적은?",
    type: "STAFF",
    options: [
      "A. 모델 정확도 비교",
      "B. 하드웨어 리소스 측정",
      "C. 데이터의 분포와 특성 파악",
      "D. 사용자 인터페이스 설계",
      "E. 보안 정책 수립"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "EDA는 데이터를 시각화하거나 통계적으로 분석하여 구조, 분포, 이상값 등을 파악하는 과정이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Data",
    title: "탐색적 데이터 분석의 목적",
    intent: "데이터 분석 초기 단계의 목적 이해",
    reference: "STAFF 교재 5장 2절 p.66"
  ),
  Question(
    id: "27",
    question: "클라우드 네이티브 환경에서 'CI/CD'의 주요 목적은?",
    type: "STAFF",
    options: [
      "A. 사용자 교육 향상",
      "B. 하드웨어 성능 분석",
      "C. 애플리케이션 개발 및 배포 자동화",
      "D. 내부 감사 프로세스 최적화",
      "E. 운영 체제 마이그레이션"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "CI/CD는 지속적인 통합과 배포를 통해 애플리케이션을 자동으로 테스트하고 배포하는 DevOps 핵심 기술이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Cloud",
    title: "CI/CD의 역할",
    intent: "DevOps에서 CI/CD가 수행하는 기능 이해",
    reference: "STAFF 교재 2장 3절 p.35"
  ),
  Question(
    id: "28",
    question: "Agile 방법론의 산출물 중 하나로 팀 작업 항목을 시각화하는 보드는?",
    type: "STAFF",
    options: [
      "A. 가넷 차트",
      "B. 워크플로우 차트",
      "C. 칸반 보드",
      "D. 마인드맵",
      "E. 의사결정 매트릭스"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "칸반 보드는 작업 항목을 '할 일', '진행 중', '완료' 등으로 구분하여 시각적으로 표현하는 도구다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "Agile",
    title: "Agile 시각화 도구",
    intent: "Agile에서 사용되는 협업 도구 이해",
    reference: "STAFF 교재 3장 3절 p.47"
  ),
  Question(
    id: "29",
    question: "AI 모델을 클라우드 환경에서 서빙(Serving)할 때 고려해야 할 요소는?",
    type: "STAFF",
    options: [
      "A. UI/UX 디자인",
      "B. 네트워크 보안만 고려",
      "C. 예측 응답 시간과 확장성",
      "D. 코드 스타일",
      "E. 오프라인 실행 최적화"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "서빙 시에는 지연 시간(latency)과 확장성(scalability)을 고려해 안정적인 AI 서비스 제공이 중요하다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "상",
    score: 10,
    topic: "AI",
    title: "AI 모델 서빙 고려사항",
    intent: "클라우드 기반 AI 서빙의 주요 요소 이해",
    reference: "STAFF 교재 4장 2절 p.55"
  ),
  Question(
    id: "30",
    question: "CX 전략에서 '옴니채널(Omnichannel)' 전략의 의미는?",
    type: "STAFF",
    options: [
      "A. 단일 채널을 집중 강화",
      "B. 모든 채널의 분리 운영",
      "C. 다양한 채널에서 일관된 고객 경험 제공",
      "D. 오프라인 중심 대응",
      "E. 채널 간 경쟁 유도"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "옴니채널은 고객이 어떤 채널을 이용하더라도 일관된 경험을 제공하는 CX 전략이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "CX",
    title: "옴니채널 전략 이해",
    intent: "다채널 환경에서 CX 전략 이해",
    reference: "STAFF 교재 5장 1절 p.61"
  ),
  Question(
    id: "31",
    question: "정보보안의 'CIA 3원칙' 중 'C'에 해당하는 것은?",
    type: "STAFF",
    options: [
      "A. Control",
      "B. Cost",
      "C. Confidentiality",
      "D. Certification",
      "E. Compliance"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "CIA는 기밀성(Confidentiality), 무결성(Integrity), 가용성(Availability)을 의미한다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "보안",
    title: "정보보안 CIA 원칙",
    intent: "기초 보안 원칙 이해",
    reference: "STAFF 교재 6장 1절 p.78"
  ),
  Question(
    id: "32",
    question: "Application Modernization에서 'Replatforming'이 의미하는 것은?",
    type: "STAFF",
    options: [
      "A. 전체 기능 재개발",
      "B. 아키텍처 변경 없이 클라우드 플랫폼으로 이동",
      "C. 데이터베이스 분리 운영",
      "D. 사용자 인터페이스 재설계",
      "E. 네트워크 중심 운영 변경"
    ],
    correctAnswer: 1,
    answer: true,
    explanation: "Replatforming은 애플리케이션 코드는 거의 변경하지 않고 플랫폼만 변경하는 방식이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Application Modernization",
    title: "Replatforming 전략 이해",
    intent: "현대화 전략 중 하나인 Replatforming 개념 이해",
    reference: "STAFF 교재 3장 1절 p.42"
  ),
  Question(
    id: "33",
    question: "클라우드에서 '가용성(Availability)' 확보를 위한 일반적인 조치로 적절한 것은?",
    type: "STAFF",
    options: [
      "A. 모든 데이터 암호화",
      "B. 접근 권한 최소화",
      "C. 다중 지역(Region) 배포",
      "D. 비용 절감 계획 수립",
      "E. 하드코딩된 설정 유지"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "가용성 확보를 위해 여러 리전(Region)에 서비스를 분산 배치하는 것이 일반적인 조치이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "상",
    score: 10,
    topic: "Cloud",
    title: "클라우드 가용성 확보 방법",
    intent: "고가용성 구성 전략 이해",
    reference: "STAFF 교재 2장 3절 p.34"
  ),
  Question(
    id: "34",
    question: "애자일에서 제품 책임자(Product Owner)의 핵심 역할은?",
    type: "STAFF",
    options: [
      "A. 테스트 자동화 수행",
      "B. 개발 업무 할당",
      "C. 제품 백로그 관리 및 우선순위 설정",
      "D. 코드 리뷰 주관",
      "E. 프로젝트 일정 산정"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "Product Owner는 제품 백로그를 관리하고 우선순위를 설정하여 팀이 고객 가치에 집중하도록 돕는다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Agile",
    title: "Product Owner 역할",
    intent: "Agile 구성원의 역할 이해",
    reference: "STAFF 교재 3장 3절 p.46"
  ),
  Question(
    id: "35",
    question: "데이터 품질 관리의 '일관성(consistency)'이 의미하는 것은?",
    type: "STAFF",
    options: [
      "A. 데이터 양이 충분함",
      "B. 분석에 사용되지 않음",
      "C. 동일한 값이 반복적으로 유지됨",
      "D. 외부 시스템과 완전히 다름",
      "E. 예외 처리가 없음"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "일관성은 동일 항목에서 동일한 방식으로 데이터가 유지되는 품질 기준이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "Data",
    title: "데이터 일관성 정의",
    intent: "데이터 품질 요소 중 일관성의 정의 이해",
    reference: "STAFF 교재 5장 2절 p.65"
  ),
  Question(
    id: "36",
    question: "보안에서 '다계층 보안(Multi-layered Security)'의 주된 목적은?",
    type: "STAFF",
    options: [
      "A. 단일 방어만 강화",
      "B. 사용자 경험 간소화",
      "C. 공격 지점마다 방어 계층을 구성",
      "D. 시스템 성능 향상",
      "E. 하드웨어 종속성 제거"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "다계층 보안은 다양한 공격 경로에 대비하기 위해 여러 계층에 방어를 설정하는 전략이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "보안",
    title: "다계층 보안의 목적",
    intent: "보안 아키텍처 설계 전략 이해",
    reference: "STAFF 교재 6장 2절 p.80"
  ),
  Question(
    id: "37",
    question: "AI 모델 학습 시 사용되는 '정규화(Normalization)' 기법의 목적은?",
    type: "STAFF",
    options: [
      "A. 데이터 누락 방지",
      "B. 데이터 간의 단위 차이를 보정",
      "C. 모델의 복잡도 감소",
      "D. GPU 사용률 증가",
      "E. 텍스트 자동 번역"
    ],
    correctAnswer: 1,
    answer: true,
    explanation: "정규화는 수치형 데이터의 범위를 일정하게 맞춰 모델 학습의 안정성과 속도를 향상시킨다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "상",
    score: 10,
    topic: "AI",
    title: "정규화 기법 목적",
    intent: "AI 모델 성능 향상을 위한 전처리 기법 이해",
    reference: "STAFF 교재 4장 2절 p.55"
  ),
  Question(
    id: "38",
    question: "애플리케이션 현대화의 일환으로 사용하는 컨테이너(Container)의 장점은?",
    type: "STAFF",
    options: [
      "A. 물리 장비 의존성 증가",
      "B. OS별 설치 필요",
      "C. 이식성 및 배포 속도 향상",
      "D. 고정 인프라 요구",
      "E. 오프라인 실행 전용"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "컨테이너는 환경 간 이식성을 높이고, 애플리케이션 배포를 빠르고 일관되게 만든다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Application Modernization",
    title: "컨테이너 활용 목적",
    intent: "현대화 기술 요소인 컨테이너의 장점 파악",
    reference: "STAFF 교재 3장 1절 p.44"
  ),
  Question(
    id: "39",
    question: "데이터 기반 서비스 설계 시 가장 우선 고려되어야 하는 항목은?",
    type: "STAFF",
    options: [
      "A. 광고 수익",
      "B. UI 애니메이션",
      "C. 활용 목적에 맞는 데이터 확보",
      "D. 테스트 장비 구비",
      "E. 벤더 평가 기준"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "서비스 설계를 위한 데이터 활용은 목적에 부합하는 고품질 데이터 확보가 우선이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "하",
    score: 10,
    topic: "Data",
    title: "데이터 기반 서비스 설계 핵심",
    intent: "데이터 활용 전제 조건 파악",
    reference: "STAFF 교재 5장 1절 p.63"
  ),
  Question(
    id: "40",
    question: "클라우드 마이그레이션 중 '하이브리드 클라우드' 전략의 특징은?",
    type: "STAFF",
    options: [
      "A. 오직 프라이빗 클라우드만 사용",
      "B. 모든 데이터를 오프라인으로 전환",
      "C. 퍼블릭과 프라이빗 환경을 혼합 활용",
      "D. 클라우드 보안을 제거",
      "E. 마이그레이션 도중 중단 전략"
    ],
    correctAnswer: 2,
    answer: true,
    explanation: "하이브리드 클라우드는 퍼블릭과 프라이빗 클라우드를 조합해 유연성을 높이는 전략이다.",
    createdAt: DateTime.now(),
    group: "staff",
    difficulty: "중",
    score: 10,
    topic: "Cloud",
    title: "하이브리드 클라우드 전략 이해",
    intent: "클라우드 마이그레이션 전략 중 하나인 하이브리드 모델 이해",
    reference: "STAFF 교재 2장 3절 p.33"
  ),
  Question(
    id: "01",
    question: "클라우드 도입 시 비용 예측이 어려운 주요 원인 중 하나는?",
    type: "BD",
    options: [
      "A. 초기 구축 비용이 고정되어 있음",
      "B. 사용량 기반 과금 모델의 특성 때문",
      "C. 계약 시 모든 리소스가 명확히 설정됨",
      "D. 하드웨어 구매 비용 포함",
      "E. 사용자가 요금제 변경 불가"
    ],
    correctAnswer: 1,
    answer: true,
    explanation: "클라우드는 Pay-as-you-go 방식으로 사용량에 따라 과금되기 때문에 정확한 사용량 예측이 어려울 수 있다.",
    createdAt: DateTime.now(),
    group: "bd",
    difficulty: "하",
    score: 10,
    topic: "Cloud",
    title: "클라우드 과금 예측의 어려움",
    intent: "클라우드 도입 시 비용 모델의 특성 이해",
    reference: "BD 교재 2장 1절 p.22"
  ),
Question(
  id: "2",
  question: "AI 프로젝트 성공을 위한 데이터 확보 측면에서 가장 중요한 요소는?",
  type: "BD",
  options: [
    "A. 최신 알고리즘 도입 여부",
    "B. 데이터의 양보다 품질",
    "C. GPU 사양",
    "D. 오픈소스 라이선스",
    "E. UX 설계"
  ],
  correctAnswer: 1,
  answer: true,
  explanation: "AI는 데이터 중심 기술로, 고품질의 정제된 데이터 확보가 성능에 핵심적이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "AI",
  title: "AI 프로젝트 데이터 품질",
  intent: "AI 추진 시 데이터 품질의 중요성 이해",
  reference: "BD 교재 4장 1절 p.41"
),
Question(
  id: "3",
  question: "애자일 조직 문화의 핵심 특징으로 적절한 것은?",
  type: "BD",
  options: [
    "A. 상명하달 방식의 명확한 지시 체계",
    "B. 문서 중심의 업무 처리",
    "C. 실패를 허용하는 실험적 문화",
    "D. 분기별 계획 수립 후 고정",
    "E. 개발팀과 운영팀의 분리"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "애자일 조직은 빠른 변화 대응을 위해 유연하고 실험적이며 자율성을 중시한다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "Agile",
  title: "애자일 조직 문화 특징",
  intent: "애자일 기반의 업무 방식 이해",
  reference: "BD 교재 3장 2절 p.35"
),
Question(
  id: "4",
  question: "SINGLEX 플랫폼의 주요 목적은?",
  type: "BD",
  options: [
    "A. 보안 장비 통합",
    "B. 클라우드 요금 자동 결제",
    "C. 데이터 기반 서비스 설계 가속화",
    "D. 업무용 PC 관리",
    "E. UI/UX 시각화 도구 제공"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "SINGLEX는 LG CNS의 데이터 기반 디지털 전환 플랫폼으로, DX 과제를 신속히 수행하도록 지원한다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "SINGLEX",
  title: "SINGLEX 플랫폼 목적",
  intent: "SINGLEX가 제공하는 기능과 가치를 이해",
  reference: "BD 교재 6장 1절 p.72"
),
Question(
  id: "5",
  question: "다음 중 CX(고객 경험) 개선을 위한 정성적 데이터로 적절한 것은?",
  type: "BD",
  options: [
    "A. 클릭 수",
    "B. 페이지 체류 시간",
    "C. 고객 인터뷰 내용",
    "D. 사용자 전환율",
    "E. 로그 수집량"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "정성적 데이터는 고객의 인식이나 감정을 담은 인터뷰, 설문 등의 비정량적 자료이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "CX",
  title: "CX 정성적 데이터 예시",
  intent: "고객 경험 개선을 위한 데이터 유형 구분",
  reference: "BD 교재 5장 1절 p.60"
),
  Question(
  id: "6",
  question: "데이터 레이크(Data Lake)의 특징으로 가장 적절한 것은?",
  type: "BD",
  options: [
    "A. 정형 데이터만 저장 가능",
    "B. 스키마 정의가 필수",
    "C. 다양한 형태의 원시 데이터를 저장",
    "D. 실시간 분석만 지원",
    "E. 관계형 DB만 통합 가능"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "데이터 레이크는 정형, 반정형, 비정형 등 다양한 원시 데이터를 저장할 수 있는 구조이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "Data",
  title: "데이터 레이크 개념",
  intent: "데이터 저장 아키텍처의 특징 이해",
  reference: "BD 교재 5장 2절 p.62"
),
Question(
  id: "7",
  question: "클라우드 환경에서 DevOps를 도입하는 주된 이유는?",
  type: "BD",
  options: [
    "A. 조직의 상명하달식 구조 강화",
    "B. 프로젝트 외주 운영",
    "C. 빠른 배포와 지속적인 통합 구현",
    "D. 보안 장비 자동화",
    "E. 마케팅 자동화"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "DevOps는 개발과 운영의 통합을 통해 빠르고 안정적인 배포와 지속적인 개선을 가능하게 한다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "Application Modernization",
  title: "DevOps 도입 목적",
  intent: "DevOps와 클라우드 환경의 연계 이해",
  reference: "BD 교재 3장 1절 p.31"
),
Question(
  id: "8",
  question: "생성형 AI(Generative AI)의 가장 일반적인 활용 예시는?",
  type: "BD",
  options: [
    "A. 바이러스 백신 개발",
    "B. 기상 예측 시스템",
    "C. 텍스트 또는 이미지 자동 생성",
    "D. 금융 거래 기록 암호화",
    "E. 네트워크 트래픽 분석"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "생성형 AI는 주어진 조건에 따라 텍스트, 이미지, 음악 등 새로운 콘텐츠를 생성한다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "AI",
  title: "생성형 AI 활용 사례",
  intent: "생성형 AI 기술의 대표적 활용 이해",
  reference: "BD 교재 4장 2절 p.44"
),
Question(
  id: "9",
  question: "애자일 조직의 '스크럼 마스터' 역할로 가장 적절한 것은?",
  type: "BD",
  options: [
    "A. 일정 관리 및 예산 통제",
    "B. 외부 이해관계자와의 계약 협상",
    "C. 팀의 장애물 제거 및 스프린트 지원",
    "D. 제품 백로그 우선순위 결정",
    "E. 코드 리뷰 주관"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "스크럼 마스터는 팀이 Agile 원칙을 따를 수 있도록 돕고, 장애물을 제거하는 역할을 한다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "Agile",
  title: "스크럼 마스터 역할",
  intent: "애자일 실행 내 조직 역할 이해",
  reference: "BD 교재 3장 2절 p.36"
),
Question(
  id: "10",
  question: "클라우드 보안에서 'Zero Trust' 모델의 핵심 원칙은?",
  type: "BD",
  options: [
    "A. 일단 접속 후에는 모든 자원 접근 허용",
    "B. 내부 사용자는 신뢰하고 외부만 검증",
    "C. 항상 검증하고 최소 권한 부여",
    "D. 보안 장비 중심의 방어",
    "E. 사후 대응 중심 정책"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "Zero Trust는 모든 접속을 기본적으로 신뢰하지 않고, 지속적으로 검증하며 최소 권한을 부여하는 보안 모델이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "보안",
  title: "Zero Trust 보안 원칙",
  intent: "현대 보안 아키텍처의 기본 원칙 이해",
  reference: "BD 교재 5장 3절 p.68"
),
Question(
  id: "11",
  question: "SINGLEX의 기반 기술로 활용되는 분석 프레임워크는?",
  type: "BD",
  options: [
    "A. Hadoop MapReduce",
    "B. Excel Macro",
    "C. D.Analytics 플랫폼",
    "D. ERP 통합 모듈",
    "E. AI 번역 API"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "SINGLEX는 D.Analytics를 기반으로 데이터 분석 및 인사이트 도출 기능을 제공한다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "SINGLEX",
  title: "SINGLEX 기술 기반 이해",
  intent: "SINGLEX 내부 분석 기술 구성 파악",
  reference: "BD 교재 6장 1절 p.74"
),
Question(
  id: "12",
  question: "클라우드 네이티브 아키텍처의 대표적 기술로 보기 어려운 것은?",
  type: "BD",
  options: [
    "A. 컨테이너",
    "B. 마이크로서비스",
    "C. CI/CD",
    "D. 단일 모놀리식 앱",
    "E. 오케스트레이션"
  ],
  correctAnswer: 3,
  answer: true,
  explanation: "모놀리식 앱은 클라우드 네이티브와 반대되는 개념으로, 분산 아키텍처를 지향하지 않는다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "Cloud",
  title: "클라우드 네이티브 구성요소 이해",
  intent: "모던 클라우드 구조의 구성 기술 파악",
  reference: "BD 교재 2장 2절 p.24"
),
Question(
  id: "13",
  question: "LG CNS의 디지털 트윈 솔루션 'PerfecTwin'의 주된 기능은?",
  type: "BD",
  options: [
    "A. 회계 업무 자동화",
    "B. 가상 공간 기반 설비 시뮬레이션",
    "C. 인사 정보 분석",
    "D. 로그 수집 시스템",
    "E. 웹사이트 UI 생성"
  ],
  correctAnswer: 1,
  answer: true,
  explanation: "PerfecTwin은 실제 설비와 동일한 가상 공간을 구축해 운영을 시뮬레이션하는 디지털 트윈 플랫폼이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "LG CNS 솔루션",
  title: "PerfecTwin 개요",
  intent: "LG CNS 디지털 트윈 기술 이해",
  reference: "BD 교재 6장 3절 p.78"
),
Question(
  id: "14",
  question: "데이터 기반 의사결정의 장점으로 가장 적절한 것은?",
  type: "BD",
  options: [
    "A. 직관적 결정 촉진",
    "B. 분석 과정 생략",
    "C. 객관성 기반 결정 가능",
    "D. 데이터 없이도 빠른 결론 도출",
    "E. 정성적 판단 강조"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "데이터 기반 결정은 객관적 근거를 통해 신뢰성 있는 의사결정을 가능하게 한다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "Data",
  title: "데이터 기반 의사결정의 이점",
  intent: "정량적 분석 기반 의사결정 장점 이해",
  reference: "BD 교재 5장 1절 p.61"
),
Question(
  id: "15",
  question: "AIDD의 주된 활용 영역은?",
  type: "BD",
  options: [
    "A. 문서 작성",
    "B. 이미지 편집",
    "C. AI 기반 마케팅 자동화",
    "D. 백신 개발",
    "E. 회계 감사"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "AIDD는 AI 기반 디지털 마케팅 자동화를 지원하는 LG CNS의 마케팅 최적화 플랫폼이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "LG CNS 솔루션",
  title: "AIDD 활용 영역",
  intent: "LG CNS 마케팅 AI 플랫폼 이해",
  reference: "BD 교재 6장 2절 p.76"
),
Question(
  id: "26",
  question: "생성형 AI의 학습 방식 중 'Self-Supervised Learning'의 특징은?",
  type: "BD",
  options: [
    "A. 완전한 정답이 있는 라벨 데이터를 사용",
    "B. 사람이 수동으로 정답을 부여",
    "C. 일부 정보를 숨기고 나머지로 예측 학습",
    "D. 사전 정의된 정책 기반 학습",
    "E. 정답 없이 무작위 학습"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "Self-Supervised Learning은 일부 데이터를 숨기고 나머지 데이터를 기반으로 예측하도록 학습하는 방식이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "상",
  score: 10,
  topic: "AI",
  title: "Self-Supervised Learning 개념",
  intent: "생성형 AI 학습 방식 이해",
  reference: "BD 교재 4장 2절 p.45"
),
Question(
  id: "27",
  question: "클라우드 마이그레이션 전략 중 'Replatform'은 어떤 방식인가?",
  type: "BD",
  options: [
    "A. 기존 시스템을 재개발",
    "B. 최소 수정으로 새로운 플랫폼에 이식",
    "C. 완전히 신규 기능 도입",
    "D. 데이터만 이전하고 코드 유지",
    "E. 인프라만 교체"
  ],
  correctAnswer: 1,
  answer: true,
  explanation: "Replatform은 코드 구조를 유지하되 플랫폼 환경에 맞게 일부 수정하는 전략이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "Cloud",
  title: "Replatform 전략",
  intent: "클라우드 전환 방식 이해",
  reference: "BD 교재 2장 3절 p.26"
),
Question(
  id: "28",
  question: "CX 전략 수립 시 고객 여정 맵(Journey Map)의 주된 목적은?",
  type: "BD",
  options: [
    "A. 내부 교육용 문서 정리",
    "B. 마케팅 예산 계획",
    "C. 고객의 경험 흐름 파악",
    "D. 서버 인프라 확인",
    "E. 브랜드 리뉴얼"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "고객 여정 맵은 고객이 서비스를 이용하는 전 과정의 경험을 시각적으로 파악하기 위해 사용된다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "CX",
  title: "고객 여정 맵의 목적",
  intent: "CX 전략 도출 도구의 활용 이해",
  reference: "BD 교재 5장 1절 p.60"
),
Question(
  id: "29",
  question: "PerfecTwin이 지원하는 산업 시뮬레이션 분야로 적절하지 않은 것은?",
  type: "BD",
  options: [
    "A. 스마트 팩토리",
    "B. 물류센터 자동화",
    "C. HR 인재 평가",
    "D. 설비 가상운영",
    "E. 에너지 효율 분석"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "PerfecTwin은 물리적 공간과 프로세스의 디지털 복제를 위한 기술로 HR 평가는 대상이 아니다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "LG CNS 솔루션",
  title: "PerfecTwin 활용 분야",
  intent: "디지털 트윈 적용 산업 이해",
  reference: "BD 교재 6장 3절 p.79"
),
Question(
  id: "30",
  question: "LG CNS의 LENA 플랫폼은 어떤 기능을 중심으로 설계되었는가?",
  type: "BD",
  options: [
    "A. 금융 리스크 시뮬레이션",
    "B. 자동화된 법률 분석",
    "C. 스마트 물류 최적화",
    "D. 엔터프라이즈 AI 기반 의사결정 지원",
    "E. 클라우드 인프라 모니터링"
  ],
  correctAnswer: 3,
  answer: true,
  explanation: "LENA는 기업 내부 데이터를 분석해 AI 기반으로 의사결정을 지원하는 LG CNS 솔루션이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "LG CNS 솔루션",
  title: "LENA 플랫폼 기능",
  intent: "LENA의 AI 기반 기업 지원 기능 파악",
  reference: "BD 교재 6장 3절 p.80"
),
Question(
  id: "31",
  question: "데이터 거버넌스의 목적 중 가장 적절한 것은?",
  type: "BD",
  options: [
    "A. 데이터 용량 축소",
    "B. 데이터 가격 책정",
    "C. 데이터 품질과 책임 기준 수립",
    "D. 시스템 사용 빈도 증가",
    "E. 알고리즘 실행 속도 개선"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "데이터 거버넌스는 데이터 품질, 보안, 책임 등의 정책과 기준을 수립·관리하기 위한 체계이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "Data",
  title: "데이터 거버넌스 목적",
  intent: "데이터 관리 체계의 핵심 목적 이해",
  reference: "BD 교재 5장 1절 p.61"
),
Question(
  id: "32",
  question: "애자일 방법론의 산출물 중 하나로, 제품의 모든 요구사항을 정리한 목록은?",
  type: "BD",
  options: [
    "A. 백로그(Backlog)",
    "B. 칸반 보드",
    "C. CI/CD 파이프라인",
    "D. 와이어프레임",
    "E. 브레인스토밍 리스트"
  ],
  correctAnswer: 0,
  answer: true,
  explanation: "제품 백로그는 제품 요구사항을 우선순위에 따라 정리한 목록으로, 애자일에서 필수 산출물이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "Agile",
  title: "제품 백로그의 정의",
  intent: "애자일 문서 구조 이해",
  reference: "BD 교재 3장 2절 p.36"
),
Question(
  id: "33",
  question: "클라우드 컴퓨팅의 핵심 이점으로 보기 어려운 것은?",
  type: "BD",
  options: [
    "A. 온디맨드 자원 확장",
    "B. 비용 효율성",
    "C. 고가용성",
    "D. 물리적 장비 의존도 증가",
    "E. 글로벌 확장성"
  ],
  correctAnswer: 3,
  answer: true,
  explanation: "클라우드는 물리적 장비에 대한 의존도를 낮추는 것이 핵심 이점 중 하나이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "Cloud",
  title: "클라우드의 이점 구분",
  intent: "클라우드 특성과 장단점 이해",
  reference: "BD 교재 2장 1절 p.22"
),
Question(
  id: "34",
  question: "데이터 분석에서 'Feature Engineering'의 주된 목적은?",
  type: "BD",
  options: [
    "A. 데이터 무결성 제거",
    "B. 분석 시간 증가",
    "C. 모델 성능 개선을 위한 입력 변수 생성",
    "D. UI 디자인 강화",
    "E. 이미지 품질 향상"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "Feature Engineering은 데이터에서 모델 성능을 높이기 위한 유의미한 변수(피처)를 추출하는 과정이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "상",
  score: 10,
  topic: "Data",
  title: "Feature Engineering 개념",
  intent: "모델 성능 향상 기법 이해",
  reference: "BD 교재 5장 2절 p.63"
),
Question(
  id: "35",
  question: "LG CNS의 AIDD가 제공하는 기능으로 가장 적절한 것은?",
  type: "BD",
  options: [
    "A. 서버 로그 분석",
    "B. AI 기반 타겟 마케팅 자동화",
    "C. 금융 리스크 평가",
    "D. 디지털 트윈 엔진 제공",
    "E. 컨테이너 오케스트레이션"
  ],
  correctAnswer: 1,
  answer: true,
  explanation: "AIDD는 AI를 활용해 마케팅 타겟팅과 콘텐츠 자동화를 지원하는 플랫폼이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "LG CNS 솔루션",
  title: "AIDD 기능 이해",
  intent: "AIDD의 마케팅 자동화 기술 파악",
  reference: "BD 교재 6장 2절 p.75"
),
Question(
  id: "36",
  question: "AI 프로젝트에서 모델 배포 후 지속적으로 수행해야 할 작업은?",
  type: "BD",
  options: [
    "A. 재학습 및 모니터링",
    "B. 알고리즘 제거",
    "C. 코드 리팩토링",
    "D. 운영 중단",
    "E. UI 색상 수정"
  ],
  correctAnswer: 0,
  answer: true,
  explanation: "모델은 배포 후에도 정확도 유지 및 성능 저하 방지를 위해 지속적인 모니터링과 재학습이 필요하다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "AI",
  title: "AI 운영 중 지속적 관리",
  intent: "AI 프로젝트 운영 단계 이해",
  reference: "BD 교재 4장 2절 p.45"
),
Question(
  id: "37",
  question: "Agile에서 스프린트(Sprint)의 일반적인 기간은?",
  type: "BD",
  options: [
    "A. 1일",
    "B. 2~4주",
    "C. 1분기",
    "D. 6개월",
    "E. 1년"
  ],
  correctAnswer: 1,
  answer: true,
  explanation: "스프린트는 일반적으로 2~4주 단위로 반복되며, 계획-개발-검토-회고의 주기를 포함한다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "Agile",
  title: "스프린트 주기 이해",
  intent: "애자일 반복 주기 이해",
  reference: "BD 교재 3장 2절 p.36"
),
Question(
  id: "38",
  question: "보안 위협 분석 시 사용하는 대표적 기법은?",
  type: "BD",
  options: [
    "A. SWOT 분석",
    "B. PEST 분석",
    "C. 위협 모델링(Threat Modeling)",
    "D. 벤치마킹",
    "E. KPI 측정"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "Threat Modeling은 보안 위협을 식별하고 방어 전략을 수립하기 위한 분석 기법이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "보안",
  title: "보안 위협 분석 기법",
  intent: "정보보안 위협 식별 기법 이해",
  reference: "BD 교재 5장 3절 p.68"
),
Question(
  id: "39",
  question: "LG CNS의 솔루션 중 디지털 전환 과제를 통합적으로 수행할 수 있도록 지원하는 플랫폼은?",
  type: "BD",
  options: [
    "A. LENA",
    "B. SINGLEX",
    "C. AIDD",
    "D. PerfecTwin",
    "E. OpenAPI Gateway"
  ],
  correctAnswer: 1,
  answer: true,
  explanation: "SINGLEX는 데이터 기반 디지털 전환 전 과정을 지원하는 통합 플랫폼이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "SINGLEX",
  title: "SINGLEX 플랫폼 기능",
  intent: "DX 수행을 위한 플랫폼 이해",
  reference: "BD 교재 6장 1절 p.73"
),
Question(
  id: "40",
  question: "LENA 플랫폼의 주요 분석 기반은 무엇인가?",
  type: "BD",
  options: [
    "A. 통계 모델",
    "B. 전문가 감",
    "C. 엔터프라이즈 데이터 분석",
    "D. 하드웨어 벤치마크",
    "E. SEO 분석"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "LENA는 기업 내부 데이터를 기반으로 한 분석을 통해 AI 기반 의사결정을 지원한다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "LG CNS 솔루션",
  title: "LENA 분석 기반 이해",
  intent: "LENA의 핵심 기능과 분석 방식 이해",
  reference: "BD 교재 6장 3절 p.80"
),
Question(
  id: "41",
  question: "AI 도입 초기 단계에서 가장 우선 고려해야 할 사항은?",
  type: "BD",
  options: [
    "A. 고성능 GPU 도입",
    "B. 다양한 알고리즘 확보",
    "C. 적용 대상 비즈니스 정의",
    "D. 외부 컨설팅 의존",
    "E. 서비스 배포 툴 선정"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "AI 도입은 기술 이전에 어떤 비즈니스에 적용할지를 명확히 정의하는 것이 우선이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "AI",
  title: "AI 도입 우선 고려사항",
  intent: "AI 프로젝트 초기 계획 수립 이해",
  reference: "BD 교재 4장 1절 p.41"
),
Question(
  id: "42",
  question: "다음 중 마이크로서비스 아키텍처(MSA)의 장점으로 적절하지 않은 것은?",
  type: "BD",
  options: [
    "A. 독립적 배포 가능",
    "B. 장애 격리 용이",
    "C. 빠른 개발 사이클",
    "D. 단일 장애 지점 증가",
    "E. 기술 스택 다양성 허용"
  ],
  correctAnswer: 3,
  answer: true,
  explanation: "MSA는 오히려 장애를 격리해 전체 시스템에 영향을 최소화할 수 있도록 설계된다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "Application Modernization",
  title: "MSA의 장점 이해",
  intent: "모던 애플리케이션 아키텍처 특성 파악",
  reference: "BD 교재 3장 1절 p.32"
),
Question(
  id: "43",
  question: "클라우드 전환 프로젝트의 사전 진단 항목으로 적절한 것은?",
  type: "BD",
  options: [
    "A. GPU 성능 평가",
    "B. 프로젝트 ROI 추정",
    "C. UI 색상 일관성",
    "D. 고객 여정 맵 작성",
    "E. 데이터 라벨링 방식 정의"
  ],
  correctAnswer: 1,
  answer: true,
  explanation: "ROI(투자대비 효과) 추정은 클라우드 전환의 타당성과 경제성을 판단하는 데 중요한 요소이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "Cloud",
  title: "클라우드 전환 사전 진단",
  intent: "클라우드 도입 전 준비 항목 이해",
  reference: "BD 교재 2장 1절 p.23"
),
Question(
  id: "44",
  question: "CX 전략에서 페르소나(Persona)를 정의하는 목적은?",
  type: "BD",
  options: [
    "A. 데이터 암호화 목적",
    "B. 내부 운영 최적화",
    "C. 주요 고객 유형에 대한 공감대 형성",
    "D. 마케팅 자동화 구현",
    "E. 시스템 확장 계획 수립"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "페르소나는 주요 고객의 특성을 대표적으로 정의해 팀 내 고객 이해도를 높이는 데 사용된다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "CX",
  title: "페르소나의 목적",
  intent: "CX 전략 설계 도구의 이해",
  reference: "BD 교재 5장 1절 p.60"
),
Question(
  id: "45",
  question: "SINGLEX 플랫폼의 주요 활용 대상은?",
  type: "BD",
  options: [
    "A. 교육용 콘텐츠 제작",
    "B. 단순 보안 설정 자동화",
    "C. 기업의 디지털 전환 과제 수행",
    "D. 개인 고객의 SNS 분석",
    "E. 브라우저 렌더링 최적화"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "SINGLEX는 기업 고객이 디지털 전환 과제를 빠르고 효율적으로 수행할 수 있도록 지원하는 플랫폼이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "SINGLEX",
  title: "SINGLEX 활용 대상",
  intent: "SINGLEX의 활용 범위 이해",
  reference: "BD 교재 6장 1절 p.72"
),
Question(
  id: "46",
  question: "생성형 AI가 기존 AI와 가장 크게 구분되는 지점은?",
  type: "BD",
  options: [
    "A. 데이터 전처리 자동화",
    "B. 알고리즘 복잡도 감소",
    "C. 새로운 콘텐츠의 생성 능력",
    "D. 연산 속도 향상",
    "E. GPU 미사용"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "생성형 AI는 기존 AI와 달리 텍스트, 이미지, 음성 등 새로운 콘텐츠를 생성할 수 있다는 점에서 차별화된다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "AI",
  title: "생성형 AI 차별점",
  intent: "기존 AI와 생성형 AI의 차이 이해",
  reference: "BD 교재 4장 2절 p.44"
),
Question(
  id: "47",
  question: "보안 사고 대응 체계에서 '사전 예방' 단계의 활동은?",
  type: "BD",
  options: [
    "A. 침해 사고 보고",
    "B. 로그 정리",
    "C. 취약점 진단 및 패치 적용",
    "D. 감사 결과 공유",
    "E. 사고 복구 문서화"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "취약점 진단과 사전 패치는 보안 사고를 방지하기 위한 예방적 조치에 해당한다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "보안",
  title: "보안 사고 예방 활동",
  intent: "보안 사고 대응 체계 이해",
  reference: "BD 교재 5장 3절 p.68"
),
Question(
  id: "48",
  question: "LENA 플랫폼이 제공하는 AI 분석의 주요 대상은?",
  type: "BD",
  options: [
    "A. 온라인 쇼핑몰 소비자 행동",
    "B. 기업 내부 프로세스 및 경영 지표",
    "C. 금융 시장 예측",
    "D. 웹페이지 색상 선호도",
    "E. 자율주행 시뮬레이션"
  ],
  correctAnswer: 1,
  answer: true,
  explanation: "LENA는 기업의 경영 활동과 내부 운영 데이터를 분석해 의사결정을 지원하는 AI 플랫폼이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "중",
  score: 10,
  topic: "LG CNS 솔루션",
  title: "LENA의 분석 대상",
  intent: "LENA의 분석 적용 범위 이해",
  reference: "BD 교재 6장 3절 p.80"
),
Question(
  id: "49",
  question: "클라우드 도입 시 기대할 수 없는 효과는?",
  type: "BD",
  options: [
    "A. 민첩한 인프라 확장",
    "B. 운영비 절감",
    "C. 수작업 중심 업무 증가",
    "D. 글로벌 서비스 대응",
    "E. 자원 사용 최적화"
  ],
  correctAnswer: 2,
  answer: true,
  explanation: "클라우드는 자동화된 운영과 효율적인 자원 활용을 통해 수작업을 줄이는 것이 일반적이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "하",
  score: 10,
  topic: "Cloud",
  title: "클라우드 도입 효과",
  intent: "클라우드 기반 환경의 기대 이점 이해",
  reference: "BD 교재 2장 1절 p.22"
),
Question(
  id: "50",
  question: "데이터 분석 프로젝트에서 '모델 드리프트(Model Drift)'가 발생하는 주요 원인은?",
  type: "BD",
  options: [
    "A. 하드웨어 성능 저하",
    "B. 데이터 분포의 변화",
    "C. 인터페이스 오류",
    "D. UI 트렌드 변화",
    "E. 로딩 속도 감소"
  ],
  correctAnswer: 1,
  answer: true,
  explanation: "모델 드리프트는 운영 환경의 변화로 인해 데이터 특성이 바뀌면서 모델 성능이 저하되는 현상이다.",
  createdAt: DateTime.now(),
  group: "bd",
  difficulty: "상",
  score: 10,
  topic: "Data",
  title: "모델 드리프트 원인",
  intent: "운영 중 데이터 변화가 미치는 영향 이해",
  reference: "BD 교재 5장 2절 p.64"
)

];
