name: techdigestcoach
description: "사내 시험 학습용 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  fl_chart: ^0.66.0
  lottie: ^2.7.0
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  # 배민체 폰트 등록
  fonts:
    - family: BMDOHYEON
      fonts:
        - asset: assets/fonts/baemin/BMDOHYEON.ttf
    - family: BMJUA
      fonts:
        - asset: assets/fonts/baemin/BMJUA.ttf
  
  assets:
    - assets/data/
    - assets/images/
    - assets/animations/
